export const sampleText = `
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dictum posuere nibh, sit amet tincidunt quam vulputate quis. Nulla ut accumsan augue. Donec sollicitudin finibus dolor venenatis scelerisque. Aenean sed elit tincidunt, placerat nisi sit amet, finibus augue. Curabitur elementum id augue a tincidunt. Aenean tortor risus, gravida sit amet tincidunt quis, tristique ut dolor. Maecenas scelerisque auctor eros, sed rhoncus ante viverra et.

  Nam eget enim augue. Quisque ornare nibh nec felis ultrices sagittis. Proin vitae massa eget dolor scelerisque vulputate quis eget lorem. Aliquam enim libero, posuere non commodo ac, iaculis quis ante. Proin sagittis neque a arcu efficitur fermentum. Nullam dictum sed neque vitae varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus rhoncus molestie pharetra. Maecenas varius, nulla nec vestibulum elementum, sapien leo aliquam nisi, quis vulputate neque metus eget nibh. Cras sapien nunc, condimentum eget arcu et, convallis consequat risus. Etiam nec sapien vitae lacus porttitor placerat. Etiam et felis convallis lectus hendrerit pellentesque. In sed ante congue, tincidunt lectus vel, convallis diam. Integer tellus turpis, dictum elementum euismod lacinia, faucibus eu mi. Sed erat magna, egestas et est vel, sodales egestas libero. Mauris dapibus, eros in aliquam porta, dui nisl tincidunt sem, iaculis iaculis ipsum turpis vitae ex.

  Praesent facilisis metus lectus, id tincidunt leo imperdiet nec. Curabitur et consequat nisi. Donec blandit mi sit amet elit vestibulum tristique. Maecenas sit amet rhoncus turpis. Suspendisse et rutrum mi, eu fermentum dolor. Quisque ipsum ligula, volutpat id dictum vitae, viverra ut massa. Suspendisse ac libero suscipit, lobortis nulla at, ultricies est. Ut pellentesque sodales eleifend. Duis imperdiet tellus sem, ac congue elit volutpat vel. Nulla malesuada tellus ac tempus pulvinar. Proin tempor dui non enim cursus pellentesque. Vivamus ullamcorper tincidunt erat vitae commodo. Pellentesque in consequat nisl. Fusce ac fringilla tellus. Quisque sollicitudin neque id mi rutrum, in tincidunt velit bibendum. Fusce pellentesque purus viverra ornare sollicitudin.

  Sed feugiat eu enim quis ornare. Donec dapibus est sed auctor fermentum. Suspendisse potenti. In eget accumsan lectus. Nullam at porta diam. Mauris sed pellentesque lorem, euismod euismod nisl. Nunc nec rhoncus ipsum. Nullam blandit ac orci id viverra. Nulla elit velit, consectetur aliquet cursus id, efficitur quis erat. Donec aliquet, massa euismod ullamcorper ultricies, felis nisi maximus sapien, vel aliquet leo neque eget risus. Aenean quis hendrerit dolor, iaculis tempus lorem.

  Cras posuere nunc vel nisi semper tincidunt. Suspendisse interdum turpis vel risus cursus, eget commodo felis lobortis. Sed quis cursus metus. Sed laoreet vehicula tellus eget auctor. Integer luctus ultricies nulla, in eleifend ligula viverra vel. Pellentesque eu blandit libero. Nam suscipit euismod magna, eu suscipit odio congue a. Sed congue ac tellus nec euismod. Phasellus lacinia mattis risus a blandit.

  Nullam pretium odio in varius consectetur. Etiam molestie nisl ut facilisis elementum. Suspendisse egestas est sit amet sagittis hendrerit. Vestibulum porta vestibulum augue convallis malesuada. Pellentesque scelerisque elit id facilisis mattis. Etiam quis facilisis mauris. Donec id turpis non sem venenatis gravida. Mauris non massa at mi malesuada tincidunt. Nullam metus turpis, venenatis tempor purus vitae, placerat cursus nisi. Praesent porta, risus at ullamcorper euismod, diam sapien imperdiet diam, ut venenatis nisi felis vitae ex. Nunc in sagittis nisl, sed laoreet dui.

  Proin tempor ut leo a venenatis. Aliquam varius lacinia imperdiet. In vitae porta quam. Suspendisse dolor nulla, cursus aliquet lorem id, sodales dignissim felis. Nullam mi dui, malesuada quis porta eu, rutrum ac leo. Ut eu sem eget eros interdum semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla ullamcorper risus nec molestie facilisis. Phasellus bibendum luctus erat, sit amet finibus sem. Aliquam ultrices aliquam ante, a aliquet leo consequat sodales. Donec elementum ornare sapien, ac vehicula ex.

  Aenean vel nunc aliquam velit semper porta. Donec sed ante dolor. Nulla vitae velit consequat, aliquam magna sit amet, efficitur massa. Duis purus ante, fringilla sit amet neque efficitur, cursus facilisis nisl. Etiam tincidunt elit ut odio blandit efficitur. Aenean sit amet mauris posuere, ultrices justo nec, ornare velit. Aliquam erat volutpat. Nullam finibus nisl ligula, at consectetur est convallis nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque sagittis ex odio, in ullamcorper augue consequat ac. Quisque mollis, tellus non scelerisque aliquam, tellus neque gravida lacus, nec aliquam nisl tellus sit amet enim.

  Donec tempor tristique nulla, ut congue dolor cursus ut. Mauris ut tortor tincidunt elit euismod sollicitudin a ac sem. Nulla semper enim risus, quis ornare neque vehicula quis. Duis vitae sapien mattis tellus rutrum interdum a eu magna. Sed non est lacus. Phasellus sollicitudin, arcu id venenatis dignissim, justo dui consectetur tellus, a congue elit lacus ut nisi. Suspendisse fermentum, mi nec aliquam efficitur, mi erat volutpat nunc, id condimentum diam neque sed sapien. Praesent dapibus sem efficitur augue faucibus, in aliquet mi eleifend. Aliquam ut viverra quam. Fusce ultrices, turpis sed bibendum porta, justo orci egestas neque, eget tempor erat mi nec magna.

  Vestibulum porttitor vehicula ligula ac convallis. Integer id mauris egestas, aliquet velit sit amet, pellentesque leo. Aliquam nec viverra nisi, nec placerat massa. Vestibulum nulla justo, molestie vitae fringilla non, convallis ac arcu. Donec nisl massa, hendrerit nec lacus a, imperdiet finibus felis. Nam congue velit risus. Quisque volutpat sed libero non ultrices. Sed et tellus commodo, tristique dolor et, varius eros. Suspendisse dui odio, scelerisque sed ante quis, posuere pellentesque erat. Proin luctus metus nec odio iaculis sodales. Pellentesque tristique mauris sodales urna fermentum mattis. Mauris ultrices nec augue vel pellentesque. Duis a bibendum quam. Phasellus tincidunt, ipsum sit amet dictum maximus, metus elit sagittis risus, hendrerit condimentum metus sem sit amet nulla. Donec gravida ultricies gravida. Quisque cursus sit amet odio vel pulvinar.
`
